version: '2.1'
services:
# CTBRec streaming recorder
  ctbrec-debian:
    image: "jafea7/ctbrec-debian"
    container_name: "CTBRec-Jafea7-Debian"
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - "${CONFIG}/ctbrec:/app/config"
      - "${MEDIA}:/app/captures"
# Uncomment the following two lines to enable logging to a file
# The files must exist **before** running the container.
#      - "${CONFIG}/ctbrec/logback.xml:/app/logback.xml"
#      - "${CONFIG}/ctbrec/server.log:/app/config/server.log"
    ports:
      - 8080:8080
      - 8443:8443
    restart: "unless-stopped"
